In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 4])
print(a)
print(type(a))

[1 2 4]
<class 'numpy.ndarray'>


In [4]:
b = np.array([1, 2, 4], dtype='float')
print(b)

[1. 2. 4.]


In [5]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(0, 10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# random
np.random.random((2, 3)) # create number between 0 and 1

array([[0.1085687 , 0.31406264, 0.53807476],
       [0.99572965, 0.3965831 , 0.37284569]])

In [10]:
# np.linspace
np.linspace(-10, 10, 10, dtype='int')

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [11]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# getting the dimensions
a1 = np.array([1, 2, 4, 5, 6])
a2 = np.arange(0, 10).reshape(5, 2)
a3 = np.arange(0, 8).reshape(2, 2, 2)
print(a1.ndim)
print(a2.ndim)  
print(a3.ndim)

1
2
3


In [13]:
# size
a1.size

5

In [14]:
# Changing Data Type
a2.astype(np.float32)
print(a2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [16]:
# arithematic operations
a2 * 2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [17]:
# relational operations
a2 > 4

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [18]:
# Array Functions
a4 = np.random.random((3, 3))
a4 = np.round(a4*100)
a4   # genarating random 3x3 matrix with values between 0 to 100

array([[28., 36.,  6.],
       [71., 31., 51.],
       [72., 21., 88.]])

In [19]:
# max/min/sum/prod
np.sum(a4)

np.float64(404.0)

In [20]:
# finding max row or column wise
print(np.max(a4, axis=0))  # column wise
print(np.max(a4, axis=1))  # row wise

[72. 36. 88.]
[36. 71. 88.]


In [22]:
# mean/mediam/std/var
print(np.mean(a4))
print(np.median(a4))
print(np.std(a4))
print(np.var(a4))

44.888888888888886
36.0
25.718322238540992
661.4320987654321


In [23]:
# trignometric functions
np.sin(a4)

array([[ 0.27090579, -0.99177885, -0.2794155 ],
       [ 0.95105465, -0.40403765,  0.67022918],
       [ 0.25382336,  0.83665564,  0.0353983 ]])

In [24]:
# dot product
a5 = np.arange(0, 12).reshape(3, 4)
a6 = np.arange(12, 24).reshape(4, 3)
np.dot(a5, a6)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [26]:
# log and exponential
print(np.log(a5))
print(" ")
print(np.exp(a5))

[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
 
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


C:\Users\amankesharwani\AppData\Local\Temp\ipykernel_34568\31985747.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a5))


In [33]:
# round/floor/ceil
a = np.random.random((2, 3))*100
print(a)
print("Rounded Values:")
print(np.round(a))
print("Floor Values:")
print(np.floor(a))
print("Ceil Values:")
print(np.ceil(a))

[[91.38733923 95.21361622 54.17795093]
 [44.9547474  89.56184823 66.06490764]]
Rounded Values:
[[91. 95. 54.]
 [45. 90. 66.]]
Floor Values:
[[91. 95. 54.]
 [44. 89. 66.]]
Ceil Values:
[[92. 96. 55.]
 [45. 90. 67.]]


In [40]:
print(a1)
print("2D")
print(a2)
print("3D")
print(a3)

[1 2 4 5 6]
2D
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
3D
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [46]:
# Indexing and Slicing
print(a1[-1])
print(a2[3, 1])  # accessing element at 4th row and 2nd column
print(a3[1, 0, 1])  # accessing element at 2nd block, 1st row and 2nd column

6
7
5


In [58]:
# slicing
print(a1[1:4])
print(a2[:,1])
print(a2[1,:])
print(" ")
print(a2[1:3, 0:2])
print(" ")
print(a3[:1, 1:2])

[2 4 5]
[1 3 5 7 9]
[2 3]
 
[[2 3]
 [4 5]]
 
[[[2 3]]]


In [59]:
# Iterating Arrays
for i in a1:
    print(i)

1
2
4
5
6


In [61]:
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9


In [62]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [63]:
# transpose
np.transpose(a2)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [65]:
# ravel -> convert n-dim array to 1-dim array
np.ravel(a3)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
# horizontal and vertical stacking
a7 = np.arange(0, 12).reshape(3,4)
a8 = np.arange(12, 24).reshape(3,4)
print(np.hstack((a7, a8)))  ## horizontal stacking
print(" ")
np.vstack((a7, a8))  ## vertical stacking


[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
 


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a8

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# splitting arrays
np.hsplit(a7, 2)   ## horizontal split into 2 arrays, means along columns

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [83]:
a10 = np.arange(0, 24).reshape(4, 6)
a10

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.vsplit(a10, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

: 