In [2]:
import numpy as np
a = np.random.randint(1, 100,25)
a

array([55, 17, 44, 12, 78, 58, 47, 64, 38, 39, 70, 69, 96, 73, 65, 12, 87,
       17, 78,  1, 74, 98, 35, 20, 16], dtype=int32)

In [4]:
# Sorting the array
np.sort(a)[::-1]  # Sorting in descending order

array([98, 96, 87, 78, 78, 74, 73, 70, 69, 65, 64, 58, 55, 47, 44, 39, 38,
       35, 20, 17, 17, 16, 12, 12,  1], dtype=int32)

In [7]:
# to add something in numpy array
a = np.append(a, 900)
a

array([ 55,  17,  44,  12,  78,  58,  47,  64,  38,  39,  70,  69,  96,
        73,  65,  12,  87,  17,  78,   1,  74,  98,  35,  20,  16, 200,
       200, 900])

In [8]:
b = np.arange(0, 24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)  # Adding a row of ones at the end

array([[ 0.,  1.,  2.,  3.,  1.],
       [ 4.,  5.,  6.,  7.,  1.],
       [ 8.,  9., 10., 11.,  1.],
       [12., 13., 14., 15.,  1.],
       [16., 17., 18., 19.,  1.],
       [20., 21., 22., 23.,  1.]])

In [19]:
# Concatenating two arrays
c = np.arange(0, 6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)
np.concatenate((c, d), axis = 0)  # Concatenating along rows

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
# Unique
e = np.array([1, 2, 2, 3, 4, 4, 5, 5, 5])
np.unique(e)

array([1, 2, 3, 4, 5])

In [ ]:
# where function
f = np.array([1, 2, 3, 40, 56, 78, 65, 43, 23, 31, 20])
np.where(f > 50) # Indices where condition is true

(array([4, 5, 6]),)

In [26]:
# replace the value greater than 50 with 0
f = np.where(f > 50, 0, f) # np.where(condition, true, false)
f

array([ 1,  2,  3, 40,  0,  0,  0, 43, 23, 31, 20])

In [28]:
# np.argmax and np.argmin
g = np.array([20, 34, 45, 67, 87, 0, 90, 65, 45, 56, 43, 32])
print(np.argmax(g))  # Index of maximum value
print(np.argmin(g))  # Index of minimum value

6
5


In [ ]:
# cumulative sum and cumulative product
h = np.array([23, 45, 56, 65, 67, 87, 89, 90, 56])
print(np.cumsum(h))
print(np.cumprod(h))

[ 23  68 124 189 256 343 432 522 578]
[              23             1035            57960          3767400
        252415800      21960174600    1954455539400  175900998546000
 9850455918576000]


In [ ]:
# percentile
i = np.array([12, 23, 34, 45, 56, 67, 78, 89, 90, 98,87,76,65,54,43,32,21])
np.percentile(i, 90)  # means 90% log peeche hain

np.float64(89.4)

In [34]:
# histogram
j = np.random.randint(1, 100, 1000)
np.histogram(j, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([ 96,  76, 109,  90, 115, 108, 108, 108,  90, 100]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
# Corelation (value between -1 to 1, 1 means strong positive corelation, 0 means not related, -1 means strong negative corelation)
salary = np.array([20000, 30000, 40000, 50000, 60000])
experience = np.array([1, 2, 3, 2, 1])
np.corrcoef(salary, experience)

array([[ 1.00000000e+00, -1.67849944e-17],
       [-1.67849944e-17,  1.00000000e+00]])

In [ ]:
# isin
k = np.array([20, 30, 40, 50, 60, 70, 80, 90])
items = np.array([23, 34, 45, 67, 89, 90, 40, 50, 20])
np.isin(k, items) # Check which elements of k are in items

array([ True, False,  True,  True, False, False, False,  True])

In [38]:
# filp
l = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.flip(l)  # Reversing the array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [39]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
np.flip(b)

array([[23, 22, 21, 20],
       [19, 18, 17, 16],
       [15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [ ]:
# put - change values at specified indices
m = np.array([11, 23, 34, 45, 56, 67, 78, 89, 90])
np.put(m, [0, 1, 2], [100, 200, 300])  # Replacing values at specified indices
m

array([100, 200, 300,  45,  56,  67,  78,  89,  90])

In [ ]:
# delete - remove elements at specified indices
n = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
np.delete(n, [0, 3, 5])  # Deleting elements at specified indices

array([ 20,  30,  50,  70,  80,  90, 100])

In [ ]:
# Set operations
# np.union1d, np.intersect1d, np.setdiff1d, np.setxor1d, np.in1d
o1 = np.array([1, 2, 3, 4, 5])
o2 = np.array([4, 5, 6, 7, 8])
print(np.union1d(o1, o2)) # Union
print(np.intersect1d(o1, o2))  # Intersection
print(np.setdiff1d(o1, o2))  # Set difference
print(np.setxor1d(o1, o2))  # Symmetric difference -> XOR
print(np.in1d(o1, o2))  # Check which elements of o1 are in o2

 

[1 2 3 4 5 6 7 8]
[4 5]
[1 2 3]
[1 2 3 6 7 8]
[False False False  True  True]


C:\Users\amankesharwani\AppData\Local\Temp\ipykernel_29816\1904959515.py:9: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(o1, o2))  # Check which elements of o1 are in o2


In [ ]:
# clip - np.clip(array, min_value, max_value)
p = np.array([12, 23, 34, 45, 56, 67, 78, 89, 90])
np.clip(p, 30, 70)  # Values less than 30 are set to 30 and greater than 70 are set to 70

array([30, 30, 34, 45, 56, 67, 70, 70, 70])